[package]
name = "m5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linreg = "0.2.0"
sdl2 = "0.35.2"

[[example]]
name = "main2"
